name=Mete Hoca Qwilino
version=1.0.0
author=Mete Hoca
maintainer=Mete Hoca <metekemalatay@gmail.com>
sentence=Unified library for all Qwilino and Modulino® Qwiic modules.
paragraph=A unified library that simplifies control of Qwilino and Modulino® I2C modules. Compatible with Arduino Uno/Nano R3, Uno/Nano R4, XIAO and other boards.
category=Communication
url=https://github.com/metehoca/Mete_Hoca_Qwilino
architectures=*
includes=Qwilino.h
depends=STM32duino VL53L4CD,STM32duino VL53L4ED,Arduino_LSM6DSOX,Arduino_LPS22HB,Arduino_HS300x,ArduinoGraphics,Arduino_LTR381RGB